# 自定义配置
my:
  properties:
    swaggerEnable: true
    filePath:
      imageFileRootPath: D:/image/ # 静态图片的本地路径

# 服务注册
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    serviceUrl:
      defaultZone: http://peer1:7001/eureka,http://peer2:7002/eureka
  instance:
    prefer-ip-address: true    # true表示使用ip地址注册
    instance-id: 管理后台服务     # 指定服务的id(Status的显示名称，可以写成IP，随意)
    ip-address: localhost

# 日志配置
logging:
  level:
    root: info
    com.fan: trace
  # 日志的路径，不指定路径在当前项目下生成spring.log日志
  path: D:/log/naicha/${spring.application.name}
  file:
    max-size: 10MB  # 日志归档的最大大小, 到了该大小就压缩打包
    max-history: 10 # 最多保存日志归档文件的数量

# mybatis-plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 下划线转驼峰
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl # 日志打印
  type-aliases-package: com.fan.**.entity.** # *Mapper.xml里resultType的类型别名
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    db-config:
      id-type: auto # id生成策略

spring:
  jackson:
    time-zone: GMT+8
    dateFormat: yyyy-MM-dd HH:mm:ss # date format

  redis:
    # 数据库索引
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 5000


  # 数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/fan_naicha?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
      username: root
      password: root